### ISSUE TITLE
Crash when selling land

### ISSUE THREAD

**Issue by ErwanScraft** [GalaxyGamesMC/iLand#43]
**Screenshots**
![Screenshot_2022-09-12-19-14-58-871_com microsoft emmx](https://user-images.githubusercontent.com/72255518/189651901-26bdc12a-99bc-42e1-b52e-0b25a73ad79c.jpg)

**Smartphone (please complete the following information):**
 - Device: Redmi 6A
 - OS: Android 
 - Browser :  edge
 - Version : 1.0.2

**Additional context**
When I was trying to sell land I suddenly left the server. I'm using the BedrockEconomy plugin as an economy plugin.

**Comment by 0xliam627** [comment]
Fixed by 534add0a893dd0c768f8ded6c9bf2ef209a49990
